# Prometheus configuration for development monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Monitor Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Monitor FastAPI application
  - job_name: 'flasx-dev'
    static_configs:
      - targets: ['flasx-dev:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Monitor PostgreSQL (if you add postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['db:5432']
    scrape_interval: 15s
    scrape_timeout: 5s

  # Monitor Redis (if you add redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 15s
    scrape_timeout: 5s
